export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const POST_TODO_SUCCESS = "POST_TODO_SUCCESS";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";

export const GET_TODO_LOADING = "GET_TODO_LOADING";
export const POST_TODO_LOADING = "POST_TODO_LOADING";
export const UPDATE_TODO_LOADING = "UPDATE_TODO_LOADING";
export const DELETE_TODO_LOADING = "DELETE_TODO_LOADING";

export const GET_TODO_FAILURE = "GET_TODO_FAILURE";
export const POST_TODO_FAILURE = "POST_TODO_FAILURE";
export const UPDATE_TODO_FAILURE = "UPDATE_TODO_FAILURE";
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE";
